project_id = "uuclwirtbkwrsbctxnpp"

[functions.hypnotherapy-chat]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.quiz-report]
verify_jwt = false

[functions.generate-oasis-test-data]
verify_jwt = false

[functions.quiz-operations]
verify_jwt = false
